# Gradle

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties

mod_id=lolmcv
mod_name=More Chest Variants
mod_version=1.5.14
mod_license=MIT
mod_group=dev.lieonlion.mcv
mod_author=LieOnLion
mod_description=Adding the much-needed Chest variants to Minecraft\nMore types to fill your builds with colourful storage.
# Links
mod_link_homepage=https://lieonlion.dev/
mod_link_sources=https://github.com/lieonlion/more-chest-variants
mod_link_issues=https://github.com/lieonlion/more-chest-variants/issues

# Common

minecraft_version=1.21.11
minecraft_fabric_version_range=~1.21.11
minecraft_neo_version_range=[1.21.11,)
java_version=21

# Fabric

fabric_version=0.139.4+1.21.11
fabric_loader_version=0.18.2
loom_version=1.14-SNAPSHOT

# NeoForge

neoforge_version=21.11.12-beta
neoforge_loader_version_range=[4,)
neoforge_moddev_version=2.0.123
neo_form_version=1.21.11-20251209.172050
# ParchmentMC
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Dependencies

# Quad Properties
quad_version=1.2.14+1.21.11
quad_version_range=~1.2.12

# Sodium Properties
sodium_version=1.21.11-0.8.1

# ModMenu Properties
modmenu_version=17.0.0-alpha.1

# YACL Properties
yacl_version=3.8.1+1.21.11