# Gradle

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties

mod_id=lolmcv
mod_name=More Chest Variants
mod_version=1.5.14
mod_license=MIT
mod_group=dev.lieonlion.mcv
mod_author=LieOnLion
mod_description=Adding the much-needed Chest variants to Minecraft\nMore types to fill your builds with colourful storage.
# Links
mod_link_homepage=https://lieonlion.dev/
mod_link_sources=https://github.com/lieonlion/more-chest-variants
mod_link_issues=https://github.com/lieonlion/more-chest-variants/issues

# Common

minecraft_version=26.1.1
minecraft_fabric_version_range=>=26.1
minecraft_neo_version_range=[26.1,)
java_version=25

# Fabric

fabric_api_version=0.145.2+26.1.1
fabric_loader_version=0.18.5
loom_version=1.15-SNAPSHOT

# NeoForge

neoforge_version=26.1.1.0-beta
neoforge_loader_version_range=[4,)
neoforge_moddev_version=2.0.141
neo_form_version=26.1.1-1

# Dependencies

# Quad Properties
quad_version=1.2.15+26.1
quad_version_range=~1.2.15

# Sodium Properties
sodium_version=26.1-0.8.7

# ModMenu Properties
modmenu_version=18.0.0-alpha.8

# YACL Properties
yacl_version=3.9.2+26.1